export enum ReservationStatus {
  PENDING = 'PENDING',
  PENDING_QUOTE = 'PENDING_QUOTE',
  QUOTE_PROVIDED = 'QUOTE_PROVIDED',
  CONFIRMED = 'CONFIRMED',
  PENDING_CONSULTATION = 'PENDING_CONSULTATION',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  NO_SHOW = 'NO_SHOW'
}
